// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/hn/feeds': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hn/feeds.get').default>>>>
    }
    '/api/hn/item': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hn/item.get').default>>>>
    }
    '/api/hn/user': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hn/user.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}